// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWP391_Mentor_Booking_System_Data;

#nullable disable

namespace SWP391_Mentor_Booking_System_Data.Migrations
{
    [DbContext(typeof(SWP391_Mentor_Booking_System_DBContext))]
    partial class SWP391_Mentor_Booking_System_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.BookingSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("MentorSlotId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("MentorSlotId");

                    b.ToTable("BookingSlots");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SwpClassId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("WalletPoint")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SwpClassId");

                    b.HasIndex("TopicId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Mentor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ApplyStatus")
                        .HasColumnType("bit");

                    b.Property<int>("NumOfSlot")
                        .HasColumnType("int");

                    b.Property<int>("PointsReceived")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.MentorSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MentorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("SkillId");

                    b.ToTable("MentorSkills");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.MentorSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingPoint")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MentorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Mode")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorSlots");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Semester", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.SwpClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MentorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("SemesterId");

                    b.ToTable("SwpClasses");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.BookingSlot", b =>
                {
                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.Group", "Group")
                        .WithMany("BookingSlots")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.MentorSlot", "MentorSlot")
                        .WithMany("BookingSlots")
                        .HasForeignKey("MentorSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MentorSlot");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Group", b =>
                {
                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.SwpClass", "SwpClass")
                        .WithMany("Groups")
                        .HasForeignKey("SwpClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.Topic", "Topic")
                        .WithMany("Groups")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SwpClass");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Mentor", b =>
                {
                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.User", "User")
                        .WithOne("Mentor")
                        .HasForeignKey("SWP391_Mentor_Booking_System_Data.Data.Mentor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.MentorSkill", b =>
                {
                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.Mentor", "Mentor")
                        .WithMany("MentorSkills")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.Skill", "Skill")
                        .WithMany("MentorSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.MentorSlot", b =>
                {
                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.Mentor", "Mentor")
                        .WithMany("MentorSlots")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Student", b =>
                {
                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("SWP391_Mentor_Booking_System_Data.Data.Student", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.SwpClass", b =>
                {
                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.Mentor", "Mentor")
                        .WithMany("SwpClasses")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.Semester", "Semester")
                        .WithMany("SwpClasses")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Topic", b =>
                {
                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.Semester", "Semester")
                        .WithMany("Topics")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.User", b =>
                {
                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.WalletTransaction", b =>
                {
                    b.HasOne("SWP391_Mentor_Booking_System_Data.Data.BookingSlot", "BookingSlot")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingSlot");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Group", b =>
                {
                    b.Navigation("BookingSlots");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Mentor", b =>
                {
                    b.Navigation("MentorSkills");

                    b.Navigation("MentorSlots");

                    b.Navigation("SwpClasses");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.MentorSlot", b =>
                {
                    b.Navigation("BookingSlots");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Semester", b =>
                {
                    b.Navigation("SwpClasses");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Skill", b =>
                {
                    b.Navigation("MentorSkills");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.SwpClass", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.Topic", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("SWP391_Mentor_Booking_System_Data.Data.User", b =>
                {
                    b.Navigation("Mentor")
                        .IsRequired();

                    b.Navigation("Student")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
